name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    name: Build and Release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-gnu
          - x86_64-apple-darwin
          - aarch64-apple-darwin
        include:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
            name: forgy-linux-x86_64
          - target: x86_64-apple-darwin
            os: macos-latest
            name: forgy-macos-x86_64
          - target: aarch64-apple-darwin
            os: macos-latest
            name: forgy-macos-arm64

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}

      - name: Install cross-compilation tools
        if: matrix.target == 'x86_64-unknown-linux-gnu'
        run: |
          sudo apt-get update
          sudo apt-get install -y musl-tools

      - name: Build binary
        run: |
          if [ "${{ matrix.target }}" = "x86_64-unknown-linux-gnu" ]; then
            cargo build --release --target ${{ matrix.target }}
          else
            cargo build --release --target ${{ matrix.target }}
          fi

      - name: Create release artifact
        run: |
          mkdir -p release
          if [ "${{ matrix.os }}" = "ubuntu-latest" ]; then
            cp target/${{ matrix.target }}/release/forgy release/${{ matrix.name }}
          else
            cp target/${{ matrix.target }}/release/forgy release/${{ matrix.name }}
          fi
          chmod +x release/${{ matrix.name }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.name }}
          path: release/${{ matrix.name }}

  create-release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts


      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            artifacts/forgy-linux-x86_64/forgy-linux-x86_64
            artifacts/forgy-macos-x86_64/forgy-macos-x86_64
            artifacts/forgy-macos-arm64/forgy-macos-arm64
          generate_release_notes: true
          draft: false
          prerelease: false