name: Release

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

jobs:
  build:
    name: Build and Release - ${{ matrix.platform.os-name }}
    strategy:
      matrix:
        platform:
          - os-name: Linux-x86_64
            runs-on: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            name: forgy-linux-x86_64
          - os-name: Linux-aarch64
            runs-on: ubuntu-latest
            target: aarch64-unknown-linux-gnu
            name: forgy-linux-arm64
          - os-name: macOS-x86_64
            runs-on: macos-latest
            target: x86_64-apple-darwin
            name: forgy-macos-x86_64
          - os-name: macOS-aarch64
            runs-on: macos-latest
            target: aarch64-apple-darwin
            name: forgy-macos-arm64
    runs-on: ${{ matrix.platform.runs-on }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build binary
        uses: houseabsolute/actions-rust-cross@v0
        with:
          command: build
          target: ${{ matrix.platform.target }}
          args: --locked --release
          strip: true

      - name: Create release artifact
        run: |
          mkdir -p release
          cp target/${{ matrix.platform.target }}/release/forgy release/${{ matrix.platform.name }}
          chmod +x release/${{ matrix.platform.name }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.platform.name }}
          path: release/${{ matrix.platform.name }}

  create-release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts

      - name: Generate release notes
        run: |
          # Get the previous tag for changelog
          PREVIOUS_TAG=$(git tag --sort=-version:refname | grep -v "^${{ github.ref_name }}$" | head -n1)
          if [ -z "$PREVIOUS_TAG" ]; then
            PREVIOUS_TAG=$(git rev-list --max-parents=0 HEAD)
          fi
          
          # Generate changelog
          echo "## What's Changed" > release_notes.md
          echo "" >> release_notes.md
          
          # Add commit messages since last tag
          git log --oneline --pretty=format:"- %s" "${PREVIOUS_TAG}..HEAD" >> release_notes.md
          
          echo "" >> release_notes.md
          echo "## Installation" >> release_notes.md
          echo "" >> release_notes.md
          echo "### Quick Install" >> release_notes.md
          echo '```bash' >> release_notes.md
          echo 'curl -fsSL https://raw.githubusercontent.com/summerua/forgy/main/install.sh | bash' >> release_notes.md
          echo '```' >> release_notes.md
          echo "" >> release_notes.md
          echo "### Manual Download" >> release_notes.md
          echo "- **Linux (x86_64)**: \`forgy-linux-x86_64\`" >> release_notes.md
          echo "- **Linux (ARM64)**: \`forgy-linux-arm64\`" >> release_notes.md
          echo "- **macOS (x86_64)**: \`forgy-macos-x86_64\`" >> release_notes.md  
          echo "- **macOS (ARM64)**: \`forgy-macos-arm64\`" >> release_notes.md

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            artifacts/forgy-linux-x86_64/forgy-linux-x86_64
            artifacts/forgy-linux-arm64/forgy-linux-arm64
            artifacts/forgy-macos-x86_64/forgy-macos-x86_64
            artifacts/forgy-macos-arm64/forgy-macos-arm64
          body_path: release_notes.md
          draft: false
          prerelease: false